#######################################################################################
# Book settings
title: "Infosec Jupyter Book"
logo: images/logo/logo.png
author: Roberto Rodriguez @Cyb3rWard0g, Jose Rodriguez (@Cyb3rPandaH)
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  The Infosec Community Definitive Guide to Jupyter Notebooks
execute:
  execute_notebooks: cache
  run_in_temp: true

html:
  favicon: images/logo/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://infosecjupyterbook.com/

repository:
  url: https://github.com/OTRF/infosec-jupyter-book
  branch: master
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true